version: '3'
services:
  foodtrack-db:
    image: ${IMAGE}
    ports: 
        - 5301:443
        - 5300:80
    restart: always 
    networks:
      - web
    labels:          
      - traefik.enable=true
      # - traefik.http.middlewares.kcenar-database-redirect-websecure.redirectscheme.scheme=https
      # - traefik.backend=foodtrack-searchengine
      - traefik.http.routers.kcenar-database.service=foodtrack-db
      - traefik.http.routers.kcenar-database.rule=Host(`db.kcenar.com`) || Host(`db.qcenar.com`)
      - traefik.http.services.foodtrack-db.loadbalancer.server.scheme=h2c
      - traefik.http.services.foodtrack-db.loadbalancer.servers.url=h2c://db.qcenar.com:5300
      # - traefik.http.routers.kcenar-database.middlewares=kcenar-database-redirect-websecure
      # - traefik.http.routers.kcenar-database.entrypoints=web
      # - traefik.http.routers.kcenar-database.rule=Host(`db.kcenar.com`) || Host(`db.qcenar.com`)
      
      # - traefik.http.routers.kcenar-database-websecure.rule=Host(`db.kcenar.com`) || Host(`db.qcenar.com`)
      # - traefik.http.routers.kcenar-database-websecure.entrypoints=websecure
      # - traefik.http.routers.kcenar-database-websecure.tls.certresolver=le
      # - traefik.http.routers.kcenar-database-websecure.tls=true
      # - traefik.http.services.kcenar-database.loadbalancer.server.scheme=h2c
      # - traefik.docker.network=web
  foodtrack-postgres:
    image: postgres 
    restart: on-failure
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=foodtrack
    volumes:
      - ./postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432
networks:
  web:
    external: true
  internal:
    external: false