version: '3'
services:
  foodtrack-db:
    image: ${IMAGE}
    ports: 
        - 5301:443
        - 5300:80
    restart: always 
  foodtrack-postgres:
    image: postgres 
    restart: on-failure
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=foodtrack
    volumes:
      - ./postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432
# version: '3'
# services:
#   foodtrack-database:
#     image: "postgres" # use latest official postgres version
#     # env_file:
#     #   - database.env # configure postgres
#     environment: 
#         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#         POSTGRES_USER: ${POSTGRES_USER} 
#         PGDATA: /var/lib/postgresql/data/pgdata
#     volumes:
#         - ${DATA}:/var/lib/postgresql
#     ports:
#         - 5432:5432