version: '3'
services:
  foodtrack-db:
    image: ${IMAGE}
    ports:
        - 5300:9000
    restart: on-failure 
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.backend=foodtrack-db
      - traefik.http.middlewares.foodtrack-db-grpc.redirectscheme.scheme=h2c      
      - traefik.http.routers.foodtrack-db.rule=Host(`db.qcenar.com`)
      - traefik.http.routers.foodtrack-db.entrypoints=grpc
      - traefik.http.routers.foodtrack-db.tls=true
      - traefik.http.routers.foodtrack-db.tls.certresolver=le
      - traefik.http.services.foodtrack-db.loadbalancer.server.scheme=h2c
      - traefik.docker.network=web
  foodtrack-postgres:
    image: postgres 
    restart: on-failure
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=foodtrack
    volumes:
      - ${DATA}/postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432
networks:
  web:
    external: true
  internal:
    external: false